# Generated by Django 5.0.4 on 2024-05-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_auto_20210902_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='address',
            field=models.CharField(blank=True, default='India', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customersignup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
